# Generated by Django 4.1.4 on 2023-01-12 14:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10, unique=True)),
                ('FullName', models.CharField(max_length=100, unique=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('ChangePct', models.FloatField(blank=True, null=True)),
                ('Image', models.URLField()),
                ('Description', models.TextField()),
            ],
            options={'ordering': ['Name']},
        ),
        migrations.CreateModel(
            name='PAN_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN', regex='[A-Z]{5}[0-9]{4}[A-Z]{1}')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pan_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
