# Generated by Django 4.1.4 on 2023-01-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0002_wallet_transactionhistory_myholdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='lastPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='referal',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
