# Generated by Django 4.1.4 on 2023-01-18 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Investments', '0003_coin_lastprice_alter_wallet_referal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myholdings',
            name='MyHoldings',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=2), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transactions',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='MyWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
