# Generated by Django 4.1.4 on 2023-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0004_alter_myholdings_myholdings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('news', models.URLField()),
                ('image', models.URLField()),
            ],
        ),
    ]
