# Generated by Django 4.1.4 on 2023-01-21 13:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Investments', '0005_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='lastPrice',
        ),
        migrations.AlterField(
            model_name='coin',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='FullName',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='Image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='Name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(default=10000),
        ),
        migrations.CreateModel(
            name='SellLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('time', models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('time', models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='myholdings',
            name='MyHoldings',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=3), blank=True, size=None),
        ),
    ]
