# Generated by Django 4.1.4 on 2023-01-22 20:17

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0006_remove_coin_lastprice_alter_coin_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AlterField(
            model_name='myholdings',
            name='MyHoldings',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=2), blank=True, size=None),
        ),
        migrations.DeleteModel(
            name='PAN_Verification',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
