# Generated by Django 4.1.4 on 2023-01-23 12:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0007_remove_wallet_user_alter_myholdings_myholdings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selllock',
            name='user',
        ),
        migrations.AlterField(
            model_name='coin',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='FullName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='Image',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='Name',
            field=models.CharField(default=' ', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BuyLock',
        ),
        migrations.DeleteModel(
            name='SellLock',
        ),
    ]
