# Generated by Django 4.1.4 on 2022-12-24 13:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Two_Factor_OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofactorotp', to='Authentication.two_factor_verification')),
            ],
        ),
        migrations.CreateModel(
            name='Email_OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emailotp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
