# Generated by Django 4.1.4 on 2023-01-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='two_factor_verification',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='two_factor_verification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
