# Generated by Django 4.1.4 on 2022-12-26 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_two_factor_otp_email_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('token', models.UUIDField()),
                ('is_verified', models.BooleanField(default=False)),
                ('token_generated_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
            ],
        ),
    ]
