# Generated by Django 4.1.4 on 2023-01-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_two_factor_verification_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile.jpg', upload_to=''),
        ),
    ]
